# This is a basic workflow to help you get started with Actions

name: packwerk valid and check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  packwerk:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 2.7.2

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: packwerk valid
        run: bundle exec packwerk validate

      - name: packwerk check
        run: bundle exec packwerk check
